config/routes.rb
AdserveExampleDe::Application.routes.draw do
  root :to => "welcome#index"
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  post "log_in" => "sessions#create", :as => "log_in"
  
  match "signup_advertiser" => "advertisers#new", :as => "signup_advertiser"
  match "signup_publisher" => "publishers#new", :as => "signup_publisher"
  match "signup_admin" => "admins#new", :as => "signup_admin"

  get "publishers_home" => "publishers#home"
  get "publishers_websites" => "publishers#websites"
  get "publishers_find_campaigns" => "publishers#find_campaigns"
  get "publishers_show_campaign" => "publishers#show_campaign"
  post "publishers_apply_for_campaign" => "publishers#apply"
  get "publishers_messages" => "publishers#messages"
  get "publishers_billing" => "publishers#billing"
  get "publishers_analysis" => "publishers#analysis"
  get "publishers_help" => "publishers#help"
  
  match "websites_add" => "websites#create", :as => "websites_add"
  post  "websites_find" => "websites#find", :as => "websites_find"

  get "advertisers_home" => "advertisers#home"
  get "advertisers_campaigns" => "advertisers#campaigns"
  get "advertisers_billing" => "advertisers#billing"
  get "advertisers_find_websites" => "advertisers#find_websites"
  get "advertisers_messages" => "advertisers#messages"
  get "advertisers_analysis" => "advertisers#analysis"
  get "advertisers_help" => "advertisers#help"
  post "advertisers_handle_message" => "advertisers#handle_message"
  
  match "campaigns_add" => "campaigns#create", :as => "campaigns_add"
  match "ads_add" => "ads#create", :as => "ads_add"
  post  "campaigns_find" => "campaigns#find", :as => "campaigns_find"
  
  get "admins_home" => "admins#home"
  get "admins_campaigns" => "admins#campaigns"
  get "admins_websites" => "admins#websites"

  resources :admins
  resources :advertisers
  resources :publishers
  resources :sessions

end

app/views/admins/campaigns.html.erb
<h2 class="title">Campaigns</h2>
<div class="inner">
	<div class="scrollable">
		<span id="show_campaigns_extender" class="scrollable-controller collapsed"> </span>
		<h4>Manage existing campaigns</h4>
		<div class="scrollable-content">
			<%= standard_table(
				[
					{ :name => 'name', :display_name => 'Name' },
					{ :name => 'overallCost', :display_name => 'Overall Cost' },
					{ :name => 'expiration_date', :display_name => 'Day of Expiration'}
				], @user.campaign) %>
		</div>
	</div>
	<div class="scrollable">
		<span id="add_campaign_extender" class="scrollable-controller collapsed"> </span>
		<h4>Add new campaign</h4>
		<div class="scrollable-content">
			<%= simple_form_for(@campaign, :url => campaigns_add_path, :html => { :class => 'form' }) do |f| %>
				<div class="group wat-cf">
					<div class="columns wat-cf" style="max-width:1000px">
						<div class="column left">
							<div class="group">
								<div class="columns">
									<div class="column left">
										<%= f.label :name %>
										<%= f.input :name, :label => false, input_html: { maxlength: 32, size: 32, class: 'text_field' } %>
									</div>
									<div class="column right">
										<%= f.label :expiration_date %>
										<%= f.input :expiration_date,  :label => false, input_html: { maxlength: 32, size: 32, class: 'text_field datepicker' } %>
									</div>
								</div>
							</div>
							<div class="group">
								<div class="columns">
									<div class="column left">
										<div class="columns">
											<div class="column left">
												<%= f.label :billing_type %>
												<%= select(:campaign, :billing_type, BillingType.constants.map {|bt| [bt.to_s.downcase.camelize, BillingType.const_get(bt)] },{include_blank: true}) %>
											</div>
											<div class="column right">
												<%= f.label :budget_type %>
												<%= select(:campaign, :budget_type, BudgetType.constants.map {|bt| [bt.to_s.downcase.camelize, BudgetType.const_get(bt)] },{include_blank: true}) %>
											</div>
										</div>
									</div>
									<div class="column right">
										<%= f.label :budget %>
										<%= f.input :budget, :label => false, input_html: { maxlength: 32, size: 32, class: 'text_field' } %>
									</div>
								</div>
							</div>
							<div class="group wat-cf">
								<div style="width:32%; float:left;">
									<div class="group">
										<%= f.label :cp_view, 'Cost Per View', :class => "string required label" %>
										<%= f.input :cp_view, :label => false, input_html: { maxlength: 32, size: 32, class: 'text_field' } %>
									</div>
								</div>
								<div style="width:32.1%; float:left; padding-left:9px;">
									<div class="group">
										<%= f.label :cp_click, 'Cost Per Click', :class => "string required label"  %>
										<%= f.input :cp_click, :label => false, input_html: { maxlength: 32, size: 32, class: 'text_field' } %>
									</div>
								</div>
								<div style="width:32.1%; float:left; padding-left:9px;">
									<div class="group">
										<%= f.label :cp_conversion, 'Cost Per Conversion', :class => "string required label"  %>
										<%= f.input :cp_conversion, :label => false, input_html: { maxlength: 32, size: 32, class: 'text_field' } %>
									</div>
								</div>
							</div>
						</div>
						<div class="column right">
							<%= f.label :categories %>
							<div class = "group bordered" style= "max-height: 40%; overflow scroll;">
								<%= f.input :categories, :as => :hidden%>
								<%= categories_table %>
							</div>
							<%= f.label :ad %>
							<div class = "group bordered" style= "max-height: 40%; overflow scroll;">
								<%= selection_table(
									[
										{ :name => 'content', :display_name => 'Content' },
										{ :name => 'viewsCount', :display_name => 'Views' },
										{ :name => 'clicksCount', :display_name => 'Clicks' },
										{ :name => 'conversionsCount', :display_name => 'Conversions'}
									], @user.ad) %>

							</div>
						</div>
						<div class="group navform wat-cf">
						<%= button_tag(type: 'submit', class: "button") do%>
							<%= image_tag('tick.png', :alt => 'Save') %> Save Campaign
						<%end%>
						<span class="text_button_padding">or</span>
						<%= link_to "Cancel", {}, :class =>  "text_button_padding link_button" %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="scrollable">
		<span id="show_ads_extender" class="scrollable-controller collapsed"> </span>
		<h4>Manage existing advertisements</h4>
		<div class="scrollable-content">
			<%= standard_table(
				[
					{ :name => 'content', :display_name => 'Content' },
					{ :name => 'viewsCount', :display_name => 'Views' },
					{ :name => 'clicksCount', :display_name => 'Clicks' },
					{ :name => 'conversionsCount', :display_name => 'Conversions'}
				], @user.ad) %>
		</div>
	</div>
	<div class="scrollable">
		<span id="add_ad_extender" class="scrollable-controller collapsed"> </span>
		<h4>Add new advertisement</h4>
		<div class="scrollable-content">
			<%= simple_form_for(@ad, :url => ads_add_path, :html => { :class => 'form' }) do |f| %>
				<div class="group wat-cf">
					<div class="columns wat-cf" style="max-width:1000px">
						<div class="group">
							<%= f.label :content %>
							<%= f.input :content, :label => false, input_html: { maxlength: 32, size: 32, class: 'text_field' } %>
						</div>
						<div class="columns">
							<div class="column left">
								<div class="group">
									<%= label_tag :ad_widh, 'Width', :class => 'string optional label' %>
									<%= text_field(:ad, :width, :size => 5, :class => 'string text_field') %>
									<%=	content_tag(:p, @ad.errors.messages[:width][0], :class =>  "error") if (@ad.errors.messages[:width].length > 0) %>
								</div>
							</div>
							<div class="column right">
								<div class="group">
									<%= label_tag(:ad_height, 'Height', :class => 'string optional label') %>
									<%= text_field(:ad, :height, :size => 5, :class => 'string text_field') %>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="group navform wat-cf">
					<%= button_tag(type: 'submit', class: "button") do%>
						<%= image_tag('tick.png', :alt => 'Save Ad') %> Save Ad
					<%end%>
					<span class="text_button_padding">or</span>
					<%= link_to "Clear", {}, :class =>  "text_button_padding link_button" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admins/help.html.erb
<h2 class="title">Help</h2>
<div class="inner">
	Some Text
</div>

app/views/admins/home.html.erb
<div class="inner">
	<h3>You have 0 active campaigns!</h3>
	<h4>Performance of your campaigns</h4>
	<div class="group">
		Some selections
	</div>
	<div class="wat-cf">
		<div class = "performanceform">
			<div class="left">
				<div class="group">
					<ul class="list">
						<li>
							<div class="left">
								<h3>Clicks:</h3>
							</div>
							<div class="item">
								<h4> 5,000 </h4>
							</div>
						</li>
						<li>
							<div class="left">
								<h3>Impressions:</h3>
							</div>
							<div class="item">
								<h4> 5,000,000 </h4>
							</div>
						</li>
						<li>
							<div class="left">
								<h3>CTR:</h3>
							</div>
							<div class="item">
								<h4> 10% </h4>
							</div>
						</li>
						<li>
							<div class="left">
								<h3>Average CPC:</h3>
							</div>
							<div class="item">
								<h4> &#8364; 0.001 </h4>
							</div>
						</li>
						<li>
							<div class="left">
								<h3>Cost:</h3>
							</div>
							<div class="item">
								<h4> &#8364; 1234 </h4>
							</div>
						</li>
					</ul>
				</div>
			</div>
			<div class="right">
				<div class="group">
					<h4>Performance Graph</h4>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admins/websites.html.erb
<h2 class="title">Find Websites</h2>
<div class="inner">
	<%= simple_form_for(@website, :url => websites_find_path, :html => { :class => 'form' }) do |f| %>
		<div class="group wat-cf"> 
			<div class="columns wat-cf" style="max-width:1000px"> 
				<div class="column left"> 
					<%= f.label :name %> 
					<%= f.input :name, :label => false, input_html: { maxlength: 32, size: 32, class: 'text_field' } %> 
				</div> 
				<div class="column right"> 
					<div class = "group bordered">
						<%= f.input :categories, :as => :hidden%>
						<%= categories_table %>
					</div>
				</div> 
			</div> 
		</div>
		<div class="group navform wat-cf">
			<%= button_tag(type: 'submit', class: "button") do%>
				<%= image_tag('tick.png', :alt => 'Search') %> Search Websites
			<%end%>
		</div>
	<% end %>
		<% if (@websites.length > 0) %>
			<%=		standard_table(
				[
					{ :name => 'name', :display_name => 'Name' },
					{ :name => 'categories', :display_name => 'Categories' }
				], @websites)%>
	<% end %>
</div>