config/routes.rb
AdserveExampleDe::Application.routes.draw do
  root :to => "welcome#index"
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  post "log_in" => "sessions#create", :as => "log_in"
  
  match "signup_advertiser" => "advertisers#new", :as => "signup_advertiser"
  match "signup_publisher" => "publishers#new", :as => "signup_publisher"
  match "signup_admin" => "admins#new", :as => "signup_admin"

  get "publishers_home" => "publishers#home"
  get "publishers_websites" => "publishers#websites"
  get "publishers_find_campaigns" => "publishers#find_campaigns"
  get "publishers_show_campaign" => "publishers#show_campaign"
  post "publishers_apply_for_campaign" => "publishers#apply"
  get "publishers_messages" => "publishers#messages"
  get "publishers_billing" => "publishers#billing"
  get "publishers_analysis" => "publishers#analysis"
  get "publishers_help" => "publishers#help"
  
  match "websites_add" => "websites#create", :as => "websites_add"
  post  "websites_find" => "websites#find", :as => "websites_find"

  get "advertisers_home" => "advertisers#home"
  get "advertisers_campaigns" => "advertisers#campaigns"
  get "advertisers_billing" => "advertisers#billing"
  get "advertisers_find_websites" => "advertisers#find_websites"
  get "advertisers_messages" => "advertisers#messages"
  get "advertisers_analysis" => "advertisers#analysis"
  get "advertisers_help" => "advertisers#help"
  post "advertisers_handle_message" => "advertisers#handle_message"
  
  match "campaigns_add" => "campaigns#create", :as => "campaigns_add"
  match "ads_add" => "ads#create", :as => "ads_add"
  post  "campaigns_find" => "campaigns#find", :as => "campaigns_find"
  
  get "admins_home" => "admins#home"
  get "admins_campaigns" => "admins#campaigns"
  get "admins_websites" => "admins#websites"

  resources :admins
  resources :advertisers
  resources :publishers
  resources :sessions

end

app/models/publisher.rb
class Publisher < User
  #TODO: Budget stuff klären
  has_many :website
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController

  include Query

  def new
    @user = Publisher.new
    render :action => "/users/new", :layout => 'application'
  end

  def home
    @menuindex = 0
  end

  def websites
    @menuindex = 1
    
    @user = Publisher.retrieve(session[:user_id])
    @website = Website.new(session.delete(:website) || {})
    errors = session.delete(:errors)
    unless errors.nil?
      errors.each do |k,v|
        v.each {|value| @website.errors.add(k,value)}
      end
    end
  end
  
  def show_campaign
    @menuindex = 2
    @user ||= Publisher.retrieve(session[:user_id])
    @campaign = Campaign.retrieve(params[:id])
  end

  def find_campaigns
    @menuindex = 2

    @campaign = Campaign.new
    @campaigns = session[:campaigns] || []
  end
 
  def billing
    @menuindex = 3
  end

  def analysis
    @menuindex = 4
  end

  def messages
    @menuindex = 5

    @messages = []
    getMessages(session[:user_id]).each do |m_hash|
      message = Message.retrieve(m_hash[:id])
      @messages << message
    end
  end

  def help
    @menuindex = 6
  end

  def create
    @user = Publisher.new(params[:publisher])
    tryToCreateUser
  end
  
  def apply
  campaign_hash = session.delete(:campaigns).first
  @campaign = Campaign.retrieve(campaign_hash[:id])
  
  message = Message.new
  message.sender = Publisher.retrieve(session[:user_id])

  message.recipient = @campaign.advertiser
  
  intevent = Intevent.applicationEvent
  intevent.message = message
  
  intevent.ids << @campaign.id
  
  zone_ids = {}
  params.delete_if { |k,v| v != "1" || !k.to_s.start_with?("zone_") }.each_key do |key|
    zone_key = key[5..36]
    ad_key = key[41..72]
    if zone_ids[zone_key].nil?
      zone_ids[zone_key] = [ad_key]
    elsif
      zone_ids[zone_key] << ad_key
    end
  end

  intevent.ids << zone_ids
  message.content = " "
  message.intevent << intevent
  message.save!

  redirect_to publishers_home_path, :notice => "You applied for the campaign. It's owner will be notified and he will get in contact with you."
  end

  def update
    @user = Publisher.new(params[:publisher])
    begin
      #TODO UserUpdating!
      Publisher.retrieve(@user.id)
    rescue
      tryToCreateUser
    end
  end

  def tryToCreateUser
    if @user.save
      @user = Publisher.retrieve(@user.id)

      session[:user_id] = @user.id
      redirect_to publishers_home_path, :notice => "You successfully signed up " + @user.full_name
    else
      render :action => "/users/new", :layout => 'application'
    end
  end

end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/analysis.html.erb
<h2 class="title">Analysis</h2>
<div class="inner">
	Some Text
</div>

app/views/publishers/billing.html.erb
<h2 class="title">Billing</h2>
<div class="inner">
	Some Text
</div>

app/views/publishers/find_campaigns.html.erb
<h2 class="title">Find Campaigns</h2>
<div class="inner">
	<%= simple_form_for(@campaign, :url => campaigns_find_path, :html => { :class => 'form' }) do |f| %>
		<div class="group wat-cf">
			<div class="columns wat-cf" style="max-width:1000px">
				<div class="column left">
					<%= f.label :name %>
					<%= f.input :name, :label => false, input_html: { maxlength: 32, size: 32, class: 'text_field' } %>
				</div>
				<div class="column right">
					<%= f.label :categories%>
					<div class = "group bordered">
						<%= f.input :categories, :as => :hidden%>
						<%= categories_table %>
					</div>
				</div>
			</div>
		</div>
		<div class="group navform wat-cf">
			<%= button_tag(type: 'submit', class: "button") do%>
				<%= image_tag('tick.png', :alt => 'Search') %> Search Campaigns
			<%end%>
		</div>
	<% end %>
	<% if (@campaigns.length > 0) %>
		<%=
			inspect_id_table(
			[
				{ :name => 'name', :display_name => 'Name' },
				{ :name => 'categories', :display_name => 'Categories' },
				{ :name => 'expiration_date', :display_name => 'Date of Expiration' },
				{ :name => 'cp_view', :display_name => 'Cost Per View'},
				{ :name => 'cp_click', :display_name => 'Cost Per Click'},
				{ :name => 'cp_conversion', :display_name => 'Cost Per Conversion'}
			], @campaigns)%>
	<% end %>
</div>

app/views/publishers/help.html.erb
<h2 class="title">Help</h2>
<div class="inner">
	Some Text
</div>

app/views/publishers/home.html.erb
<div class="inner">
	<h3>You have 0 websites!</h3>
	<h4>Performance of your websites</h4>
	<div class="group">
		Some selections
	</div>
	<div class="wat-cf">
		<div class = "performanceform">
			<div class="left">
				<div class="group">
					<ul class="list">
						<li>
							<div class="left">
								<h3>Clicks:</h3>
							</div>
							<div class="item">
								<h4> 5,000 </h4>
							</div>
						</li>
						<li>
							<div class="left">
								<h3>Impressions:</h3>
							</div>
							<div class="item">
								<h4> 5,000,000 </h4>
							</div>
						</li>
						<li>
							<div class="left">
								<h3>CTR:</h3>
							</div>
							<div class="item">
								<h4> 10% </h4>
							</div>
						</li>
						<li>
							<div class="left">
								<h3>Income:</h3>
							</div>
							<div class="item">
								<h4> &#8364; 1234 </h4>
							</div>
						</li>
					</ul>
				</div>
			</div>
			<div class="right">
				<div class="group">
					<h4>Performance Graph</h4>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/publishers/messages.html.erb
<div class="inner">
	<%= render partial: "shared/messages", locals: {messages: @messages} %>
</div>

app/views/publishers/show_campaign.html.erb
<h2 class="title">Campaign Details</h2>
<div class="inner">
	<!-- TODO: Built in back button -->
	<h3><%=@campaign.name%></h3>
	<div class="form">
		<div class="columns wat-cf top-padded" style="max-width:1000px">
			<div class="column left">
				<hr>
				<div class="group wat-cf">
					<label class="label left">Target URL </label>
					<p class="right"> <%= @campaign.target_url%> </p>
				</div>
				<hr>
				<div class="group wat-cf">
					<label class="label left">Expiration Date </label>
					<p class="right"> <%= @campaign.expiration_date%></p>
				</div>
				<hr>
				<div class="group wat-cf">
					<label class="label left">Billing Type </label>
					<p class="right"> <%= @campaign.billing_type%></p>
				</div>
				<hr>
				<div class="group wat-cf">
					<label class="label left">Cost per View </label>
					<p class="right"> <%= @campaign.cp_view%></p>
				</div>
				<hr>
				<div class="group wat-cf">
					<label class="label left">Cost per Click</label>
					<p class="right"> <%= @campaign.cp_click%></p>
				</div>
				<hr>
				<div class="group wat-cf">
					<label class="label left">Cost per Conversion</label>
					<p class="right"> <%= @campaign.cp_conversion%></p>
				</div>
			</div>
			<div class="column right">
				<hr>
				<div class="group wat-cf">
					<label class="label left">Categories</label>
					<p class="right"> <%= @campaign.categories %></p>
				</div>
				<hr>
				<div class="group">
					<label class="label">Advertisements</label>
					<%= standard_table(
						[
							{ :name => 'content', :display_name => 'Content' },
							{ :name => 'viewsCount', :display_name => 'Views' },
							{ :name => 'clicksCount', :display_name => 'Clicks' },
							{ :name => 'conversionsCount', :display_name => 'Conversions'}
						], @campaign.ad) %>
				</div>
			</div>
		</div>
	</div>
	<h3>Apply for this campaign</h3>
	<h4> Your websites:</h4>
	<%= simple_form_for(@campaign,
											:url => url_for(:action => 'apply', :controller => 'publishers'),
											:html => { :class => 'form' },
											:method => 'post') do |f| %>
		<% @user.website.each do |website| %>
			<div class="scrollable">
				<div class="group wat-cf">
					<div class="left">
						<span id="show_websites_extender" class="scrollable-controller collapsed"> </span>
						<p> <%= website.name %> <p>
					</div>
				</div>
				<div class="scrollable-content wat-cf">
					<div class="group wat-cf">
						<div class="left">
							<p> Zones </p>
							<%= clickable_table(
								[
									{ :name => 'width', :display_name => 'Width' },
									{ :name => 'height', :display_name => 'Height' },
								], website.zone)
							%>
					</div>
					<div class="right">
						<p> Advertisements </p>
						<p id="help_text"> Click on one of the rows in the zone table to choose ads for this zone. </p>
						<% website.zone.each do |zone| %>
							<div id=<%="adsforzone_#{zone.id}"%> style="display:none">
								<%= ad_for_zone_table(
									[
										{ :name => 'content', :display_name => 'Content' },
									],@campaign.ad, zone.id) %>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	<%end%>
	<div class="group navform wat-cf">
		<%= button_tag(type: 'submit', class: "button") do%>
			<%= image_tag('tick.png', :alt => 'Send Application') %> Send Application
		<%end%>
	</div>
	<% end %>
</div>

app/views/publishers/websites.html.erb
<h2 class="title">Websites</h2>
<div class="inner">
	<div class="scrollable">
		<span id="show_websites_extender" class="scrollable-controller collapsed"> </span>
		<h4>Manage existing websites</h4>
		<div class="scrollable-content">
			<%= standard_table(
				[
					{ :name => 'name', :display_name => 'Name' },
					{ :name => 'description', :display_name => 'Description' },
				], @user.website) %>
		</div>
	</div>
	<div class="scrollable">
		<span id="add_website_extender" class="scrollable-controller collapsed" ></span>
		<h4>Add Website </h4>
		<div class="scrollable-content">
			<%= simple_form_for(@website, :url => websites_add_path, :html => { :class => 'form' }) do |f| %>
				<div class="columns wat-cf" style="max-width:1000px">
					<div class="column left"> 
						<div class="group">
							<%= f.label :name %>
							<%= f.input :name, :label => false, input_html: { maxlength: 32, size: 32, class: 'text_field' } %>
						</div>
						<div class="group">
							<%= f.label :base_url %>
							<%= f.input :base_url, :label => false, input_html: { maxlength: 64, class: 'text_field' } %>
						</div>
						<div class="group">
							<%= f.label :description %>
							<%= f.input :description, as: :text, :label => false, input_html: { class: 'text_area' } %>
						</div>
					</div>
					<div class="column right">
						<%= f.label :categories %>
						<div class = "group bordered" style= "max-height: 40%; overflow scroll;">
							<%= f.input :categories, :as => :hidden%>
							<%= categories_table %>
						</div>
						<div class = "group">
							<%= f.label :zone, 'Zones', :class => 'string optional label' %>
							<%= standard_table(
								[
									{ :name => 'size.width', :display_name => 'Width' },
									{ :name => 'size.height', :display_name => 'Height' },
								], @website.zone, "zone_table")
							%>
						<div class="columns">
							<%= f.input :zone_strings, :as => :hidden%>
							<div class="column left">
								<div class="group">
									<%= label_tag :zone_widh, 'Width', :class => 'string optional label' %>
									<%= text_field(:zone, :width, :size => 5, :class => 'string text_field') %>
								</div>
							</div>
							<div class="column right">
								<div class="group">
									<%= label_tag(:zone_height, 'Height', :class => 'string optional label') %>
									<%= text_field(:zone, :height, :size => 5, :class => 'string text_field') %>
								</div>
							</div>
							<p class="clickable" onClick="addZone();">Add Zone</p>
						</div>
					</div>
				</div>
			</div>
			<div class="group navform wat-cf">
				<%= button_tag(type: 'submit', class: "button") do%>
					<%= image_tag('tick.png', :alt => 'Save Website') %> Save Website
				<%end%>
				<span class="text_button_padding">or</span>
				<%= link_to "Cancel", {}, :class =>  "text_button_padding link_button" %>
			</div>
		<% end %>
	</div>
</div>