config/routes.rb
AdserveExampleDe::Application.routes.draw do
  root :to => "welcome#index"
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  post "log_in" => "sessions#create", :as => "log_in"
  
  match "signup_advertiser" => "advertisers#new", :as => "signup_advertiser"
  match "signup_publisher" => "publishers#new", :as => "signup_publisher"
  match "signup_admin" => "admins#new", :as => "signup_admin"

  get "publishers_home" => "publishers#home"
  get "publishers_websites" => "publishers#websites"
  get "publishers_find_campaigns" => "publishers#find_campaigns"
  get "publishers_show_campaign" => "publishers#show_campaign"
  post "publishers_apply_for_campaign" => "publishers#apply"
  get "publishers_messages" => "publishers#messages"
  get "publishers_billing" => "publishers#billing"
  get "publishers_analysis" => "publishers#analysis"
  get "publishers_help" => "publishers#help"
  
  match "websites_add" => "websites#create", :as => "websites_add"
  post  "websites_find" => "websites#find", :as => "websites_find"

  get "advertisers_home" => "advertisers#home"
  get "advertisers_campaigns" => "advertisers#campaigns"
  get "advertisers_billing" => "advertisers#billing"
  get "advertisers_find_websites" => "advertisers#find_websites"
  get "advertisers_messages" => "advertisers#messages"
  get "advertisers_analysis" => "advertisers#analysis"
  get "advertisers_help" => "advertisers#help"
  post "advertisers_handle_message" => "advertisers#handle_message"
  
  match "campaigns_add" => "campaigns#create", :as => "campaigns_add"
  match "ads_add" => "ads#create", :as => "ads_add"
  post  "campaigns_find" => "campaigns#find", :as => "campaigns_find"
  
  get "admins_home" => "admins#home"
  get "admins_campaigns" => "admins#campaigns"
  get "admins_websites" => "admins#websites"

  resources :admins
  resources :advertisers
  resources :publishers
  resources :sessions

end

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>AdServe</title>
		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div id="container">
			<div id="header">
				<h1><a href="/">AdServe</a></h1>
				<div id="user-navigation">
					<ul class="wat-cf">
						<li>
							Logged in as <%= current_user.full_name %>
						</li>
						<li>
							<a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a>
						</li>
						<li>
							<a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a>
						</li>
						<li>
							<a href="/log_out" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a>
						</li>
					</ul>
				</div>
				<div id="main-navigation">
					<ul class="wat-cf"></ul>
				</div>
			</div>
			<div id="wrapper" class="wat-cf">
				<div id="main">
					<div class="flash">
						<% flash.each do |type, message| -%>
						<div class="message <%= type %>">
							<p>
								<%= message %>
							</p>
						</div>
						<% end -%>
					</div>
					<div class="block" id="block-tables">
						<div class="secondary-navigation">
							<ul class="wat-cf">
								<li class="<%= @menuindex== 0 ? "first current" : "first"%>">
								<%= link_to "Home", admins_home_path %>
								</li>
								<li class="<%= @menuindex== 1 ? "current": ""%>">
								<%= link_to "Administrate Campaigns", admins_campaigns_path %>
								</li>
								<li class="<%= @menuindex== 2 ? "current": ""%>">
								<%= link_to "Administrate Websites", admins_websites_path %>
								</li>
								<li class="<%= @menuindex== 5 ? "last current" : "last"%>">
								<%= link_to "Help", advertisers_help_path %>
								</li>
							</ul>
						</div>
						<div class="content">
							<%= yield %>
						</div>
					</div>

					<div id="footer">
						<div class="block">
							<p>
								Copyright &copy; <%= Time.now.year %> AdServe.
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/layouts/advertisers.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>AdServe</title>
		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div id="container">
			<div id="header">
				<h1><a href="/">AdServe</a></h1>
				<div id="user-navigation">
					<ul class="wat-cf">
						<li>
							Logged in as <%= current_user.full_name %>
						</li>
						<li>
							<a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a>
						</li>
						<li>
							<a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a>
						</li>
						<li>
							<a href="/log_out" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a>
						</li>
					</ul>
				</div>
				<div id="main-navigation">
					<ul class="wat-cf"></ul>
				</div>
			</div>
			<div id="wrapper" class="wat-cf">
				<div id="main">
					<div class="flash">
						<% flash.each do |type, message| -%>
						<div class="message <%= type %>">
							<p>
								<%= message %>
							</p>
						</div>
						<% end -%>
					</div>
					<div class="block" id="block-tables">
						<div class="secondary-navigation">
							<ul class="wat-cf">
								<li class="<%= @menuindex== 0 ? "first current" : "first"%>">
								<%= link_to "Home", advertisers_home_path %>
								</li>
								<li class="<%= @menuindex== 1 ? "current": ""%>">
								<%= link_to "Campaigns", advertisers_campaigns_path %>
								</li>
								<li class="<%= @menuindex== 2 ? "current": ""%>">
								<%= link_to "Find Websites", advertisers_find_websites_path %>
								</li>
								<li class="<%= @menuindex== 3 ? "current" : ""%>">
								<%= link_to "Billing", advertisers_billing_path %>
								</li>
								<li class="<%= @menuindex== 4 ? "current" : ""%>">
								<%= link_to "Analysis", advertisers_analysis_path %>
								</li>
								<li class="<%= @menuindex== 5 ? "current" : ""%>">
								<%= link_to "Messages", advertisers_messages_path %>
								</li>
								<li class="<%= @menuindex== 6 ? "last current" : "last"%>">
								<%= link_to "Help", advertisers_help_path %>
								</li>
							</ul>
						</div>
						<div class="content">
							<%= yield %>
						</div>
					</div>

					<div id="footer">
						<div class="block">
							<p>
								Copyright &copy; <%= Time.now.year %> AdServe.
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>AdServe</title>
		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div id="container">
			<div id="header">
				<h1><a href="/">AdServe</a></h1>
				<div id="user-navigation">
					<ul class="wat-cf">
						<li>
							<%= link_to "Sign Up", signup_advertiser_path %> | <%= link_to "Log in", log_in_path %>
						</li>
					</ul>
				</div>
				<div id="main-navigation">
					<ul class="wat-cf"></ul>
				</div>
			</div>
			<div id="wrapper" class="wat-cf">
				<div id="main">
					<div class="flash">
						<% flash.each do |type, message| -%>
						<div class="message <%= type %>">
							<p>
								<%= message %>
							</p>
						</div>
						<% end -%>
					</div>
					<%= yield %>
					<div id="footer">
						<div class="block">
							<p>
								Copyright &copy; <%= Time.now.year %> AdServe.
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/layouts/publishers.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>AdServe</title>
		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div id="container">
			<div id="header">
				<h1><a href="/">AdServe</a></h1>
				<div id="user-navigation">
					<ul class="wat-cf">
						<li>
							Logged in as <%= current_user.full_name %>
						</li>
						<li>
							<a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a>
						</li>
						<li>
							<a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a>
						</li>
						<li>
							<a href="/log_out" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a>
						</li>
					</ul>
				</div>
				<div id="main-navigation">
					<ul class="wat-cf"></ul>
				</div>
			</div>
			<div id="wrapper" class="wat-cf">
				<div id="main">
					<div class="flash">
						<% flash.each do |type, message| -%>
						<div class="message <%= type %>">
							<p>
							<%= message %>
							</p>
						</div>
					<% end -%>
				</div>					
				<div class="block" id="block-tables">
					<div class="secondary-navigation">
						<ul class="wat-cf">
							<li class="<%= @menuindex== 0 ? "first current" : "first"%>">
							<%= link_to "Home", publishers_home_path %>
							</li>
							<li class="<%= @menuindex== 1 ? "current": ""%>">
							<%= link_to "Websites", publishers_websites_path %>
							</li>
							<li class="<%= @menuindex== 2 ? "current": ""%>">
							<%= link_to "Find Campaigns", publishers_find_campaigns_path %>
							</li>

							<li class="<%= @menuindex== 3 ? "current" : ""%>">
							<%= link_to "Billing", publishers_billing_path %>
							</li>
							<li class="<%= @menuindex== 4 ? "current" : ""%>">
							<%= link_to "Analysis", publishers_analysis_path %>
							</li>
							<li class="<%= @menuindex== 5 ? "current" : ""%>">
							<%= link_to "Messages", publishers_messages_path %>
							</li>
							<li class="<%= @menuindex== 6 ? "last current" : "last"%>">
							<%= link_to "Help", publishers_help_path %>
							</li>
						</ul>
					</div>
					<div class="content">
						<%= yield %>
					</div>
				</div>
				<div id="footer">
					<div class="block">
						<p>
						Copyright &copy; <%= Time.now.year %> AdServe.
						</p>
					</div>
				</div>
			</div>
			</div>
		</div>
	</body>
</html>